services:
  - type: web
    name: clear-ai-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
